### ISSUE TITLE
Compile issue on OS X

### ISSUE THREAD

**Issue by Shoozza** [Murii/CLove#19]
CLove/src/graphics/graphics.h:89:1: error: unknown type name 'SDL_Window'
SDL_Window* graphics_getWindow(void);
^
1 error generated.
make[2]: *** [CMakeFiles/love.dir/src/graphics/batch.c.o] Error 1
make[1]: *** [CMakeFiles/love.dir/all] Error 2
make: *** [all] Error 2

I thought SDL2 dependencies were removed?

**Comment by Murii** [comment]
Should be fixed, please check now.

**Comment by Shoozza** [comment]
Yes, thanks!
