### ISSUE TITLE
PhysicsFS: File System Mounting

### ISSUE THREAD

**Issue by RobLoach** [Murii/CLove#36]
Bring in PhysFS to allow mounting a .love file, and allow running games from different directories.

PhysFS 3.0 is also in the works:
https://www.patreon.com/posts/project-3-0-12780949

Would also allow the implementation of [love.filesystem.mount()](https://love2d.org/wiki/love.filesystem.mount).

The other part to this would be updating the file loading to go through PhysFS rather than directly from the disk.

**Comment by Murii** [comment]
I've been thinking in adding this feature but wasn't really sure about it. I'll put it as my next task on the TODO list.

**Comment by RobLoach** [comment]
Not needed anytime soon. Thought I'd put it on the wish list 😎

**Comment by Murii** [comment]
As of 0.7.1 Physfs is the default filesystem manager. 
I think I added all the features required.
https://github.com/Murii/CLove/commit/8a8fe3c7793bae0230dd376ec45cc06aa2b685a3

**Comment by RobLoach** [comment]
Wow, nicely done! Smart use of checking PHYSFS availability, and falling back to normal filesystem calls if not.
