### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by RobLoach** [Murii/CLove#44]
When running `clove main.lua` with the latest `master`, with the following, I get a segfault....

``` lua
function love.draw()
	-- Nothing
end
```

Linux, cmake 3.5.1 gcc 5.4.1

Is there a way to enable debugging?

**Comment by Murii** [comment]
Thanks for pointing out the issue! I tested the code only on OS X and here everything is fine but on Linux is not apparently. 
Here's the fix: https://github.com/Murii/CLove/commit/1494e18d1682545763fe6ae2c19d5550f5dcc46b
If you are interested in the process of debugging you can use gdb.

**Comment by RobLoach** [comment]
> Here's the fix: 1494e18

Ah, that makes sense. Good find! Confirmed fixed. :+1:
