### ISSUE TITLE
Just some questions before I test

### ISSUE THREAD

**Issue by JacobSinclair** [Murii/CLove#45]
Hey, I looked at this and though that it looked so much better than regular Love2D. However, I have some questions:

- Does it support LZMA/7z for the game packages?
- Does it have 3D yet as said on the forums?
- Can it read Zips/7zs/other archive type inside the game's package (So, I could have a .7z file containing other things that might take up lots of space (for example, if its's 3D I might want to put all models in 1 archive and all the textures in another)
- You said there is native C code support, how would I go about using that? And how easy is it to integrate with lua?

Thanks in advance!

**Comment by Murii** [comment]
If you are interested in knowing what archive formats are supported check out: https://icculus.org/physfs/
The whole idea of 3D has been put aside for now. 
If you are interested in coding in C check out: https://github.com/Murii/CLove/tree/master/native . Basically you can have your main.lua file with some data or no data at all and have all the logic made inside your .c files which will be called inside game.c. By coding your game logic in C you will be able to use the whole framework as you please including the 3rdparty libs.

**Comment by JacobSinclair** [comment]
@Murii Thanks! This will be more useful than Love2D (atleast for me) because I am used to Rust, and I can do some minimal C to call code from a Dll I wrote in rust. Although, could I suggest native Rust support? Many people consider it "The language to kill C/C++" (although it is unlikely that C will die). It is a safer language and is about as fast as C. Also, it's build system is amazing. (Google "Rust cargo" for more info on the build system)

**Comment by Murii** [comment]
@JacobSinclair 
I'm planning in adding support for my upcoming scripting language (Deea, Lisp like) in CLove.
This is because I want to start using fewer 3rdparty software and make more things by myself.
But yeah, who knows? CLove is a long term project which I want to work on for many years, everything is possible :)
